name: Deploy to nft-minter.herokuapp.com

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          envkey_MNEMONIC: ${{ secrets.MNEMONIC }}
          envkey_INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          envkey_PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          envkey_PINATA_SECRET_API_KEY:  ${{ secrets.PINATA_SECRET_API_KEY }}
          envkey_PREDEFINED_GITHUB_GIST_ID:  ${{ secrets.PREDEFINED_GITHUB_GIST_ID }}
          envkey_METADATA_LOCATION:  ${{ secrets.METADATA_LOCATION }}

          file_name: .env

      - name: Make react envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_PREDEFINED_GITHUB_GIST_ID:  ${{ secrets.PREDEFINED_GITHUB_GIST_ID }}
          envkey_REACT_APP_API_URL:  ${{ secrets.REACT_APP_API_URL }}
          envkey_REACT_APP_INFURA_API_KEY:  ${{ secrets.REACT_APP_INFURA_API_KEY }}

          file_name: packages/client/.env

      - name: Make server envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MNEMONIC:  ${{ secrets.MNEMONIC }}
          envkey_INFURA_API_KEY:  ${{ secrets.INFURA_API_KEY }}

          file_name: packages/server/.env

      - name: Log in Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY:  ${{ secrets.PINATA_SECRET_API_KEY }}
          METADATA_LOCATION: ${{ secrets.METADATA_LOCATION }}

      - name: Push to Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:push -a nft-minter web 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY:  ${{ secrets.PINATA_SECRET_API_KEY }}
          METADATA_LOCATION: ${{ secrets.METADATA_LOCATION }}

      - name: Release in Heroku
        uses: sjdonado/heroku@master
        with:
          args: container:release -a nft-minter web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY:  ${{ secrets.PINATA_SECRET_API_KEY }}
          METADATA_LOCATION: ${{ secrets.METADATA_LOCATION }}
          